name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy_production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH keys and dependencies
        run: |
          sudo apt-get update && sudo apt-get install rsync -y && sudo apt-get install openssh-server -y
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_DEPLOY_KEY_PROD_2 }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 43.206.28.112 >> ~/.ssh/known_hosts
          echo "${{ secrets.ENV_PRODUCTION_2 }}" > .env
        env:
          PRIVATE_DEPLOY_KEY_PROD_2: ${{ secrets.PRIVATE_DEPLOY_KEY_PROD_2 }}
          ENV_PRODUCTION_2: ${{ secrets.ENV_PRODUCTION_2 }}

      - name: Deploy to the second server
        run: |
          rsync --progress -avzh -e "ssh -i ~/.ssh/id_rsa" --rsync-path="sudo rsync" --exclude='.git' --delete . ubuntu@43.206.28.112:~/clinic-test-cicd
          ssh -i ~/.ssh/id_rsa "ubuntu@43.206.28.112" "cd clinic-test-cicd && sudo mkdir loglog"

    env:
      PRIVATE_DEPLOY_KEY_PROD_2: ${{ secrets.PRIVATE_DEPLOY_KEY_PROD_2 }}
      ENV_PRODUCTION_2: ${{ secrets.ENV_PRODUCTION_2 }}
